### ISSUE TITLE
ESM does not seem to work in Node 12

### ISSUE THREAD

**Issue by David-Else** [wallabyjs/quokka#380]
### Issue description or question
I can't seem to use `import` any more in TypeScript (not tested JS)

### Sample code
This is a saved TypeScript file with .ts extension. I use Quokka start on current file.

Are you using at least this version of ESM?
https://github.com/standard-things/esm/releases/tag/3.2.23

> Fixed REPL support for Node 12 (#792)

```javascript
import { Hero } from './game-objects.js'

const x = new Hero([10, 10]);

```

### Quokka.js Console Output

```
Quokka 'test.ts' (node: v12.3.1, TypeScript: v3.5.1)​​​​
 
Unexpected token { 
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:718​
  at ​​​Object.Module._extensions..js​​​ ​internal/modules/cjs/loader.js:785​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:641​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:556​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:16​
  at ​​​Object.<anonymous>​​​ ​src/classes/test.ts:1​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:774​
```

### Code editor version
Visual Studio Code v1.35

### OS name and version
Linux Fedora 29

**Comment by smcenlly** [comment]
We couldn't duplicate this issue using the same version of node and TypeScript. We also tested using Javascript and everything was OK. Perhaps the problem is related to platform (we tested on Windows, not Linux).

Having said that, we _were_ using `esm` version 3.2.22 and have now updated to the latest, version 3.2.25.

Please update your Quokka for VS Code to the latest version (1.0.225) which will fix the problem if it was caused by `esm` and node v12 compatibility issues.

If you still have the problem, please try cloning this repo, run `npm install` and then see if you have the same behavior: https://github.com/wallabyjs/quokka-issue-380.

**Comment by ArtemGovorov** [comment]
The issue is not likely to be related to ESM, it may be related to your `tsconfig.json` settings. Looks like you are importing `.js` file from your TypeScript file, in order for `ts-node` (BTW check that you have it installed in your project or in `~/.quokka` folder) to correctly compile your `.js` (if it needs compilation), the `allowJs` setting needs to be set to `true` in your `tsconfig.json`. I would suggest to rename the file to `game-objects.ts` and try to make it work first.

**Comment by David-Else** [comment]
Hello. Thanks for your help, I followed the advice, I have solved one error, but it has generated another :(

I installed ts-node into the `~/.quokka` folder and this made @smcenlly 's test file work. I also added `allowJs` which made my original test file work with the .js extension, BUT now my entire project stops working on a certain file with this error:
```
Quokka 'app.ts' (node: v12.3.1, TypeScript: v3.5.1, plugins: jsdom-quokka-plugin)​​​​
 
src/classes/game-objects.js: Emit skipped 
  at ​​​getOutput​​​ ​/home/david/.quokka/node_modules/ts-node/src/index.ts:363​
  at ​​​Object.compile​​​ ​/home/david/.quokka/node_modules/ts-node/src/index.ts:393​
  at ​​​Module.m._compile​​​ ​/home/david/.quokka/node_modules/ts-node/src/index.ts:439​
  at ​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:785​
  at ​​​Object.require.extensions.<computed> [as .js]​​​ ​/home/david/.quokka/node_modules/ts-node/src/index.ts:442​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:641​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:556​
  at ​​​Module.require​​​ ​internal/modules/cjs/loader.js:681​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:16​
  at ​​​Object.<anonymous>​​​ ​./src/classes/factory.js:1​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:774​
  at ​​​Module.m._compile​​​ ​/home/david/.quokka/node_modules/ts-node/src/index.ts:439​
  at ​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:785​
  at ​​​Object.require.extensions.<computed> [as .js]​​​ ​/home/david/.quokka/node_modules/ts-node/src/index.ts:442​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:641​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:556​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:16​
  at ​​​Object.<anonymous>​​​ ​src/app.ts:11​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:774​

```
I have created a repo for you to look at. Please clone it and use the `npm run start-typescript-development` to compile it. Then go to the root file, `src/app.ts` and run Quokka to see the error.

https://github.com/David-Else/quokka-test

In case it is relevant, here is my `~/.quokka` package.json. The config.json is just `{ "pro": true }`

```
{
  "dependencies": {
    "canvas": "^2.5.0",
    "jsdom-quokka-plugin": "^1.0.14",
    "ts-node": "^8.2.0"
  }
}
```
Please note I need all my imports to have the .js extension so they work in the browser. TypeScript accepts that and it all seems to be working fine. apart from the Quokka integration.

**Comment by ArtemGovorov** [comment]
Thanks for creating the sample repo.

It looks like the issue is not specific to Quokka. From what I can see `ts-node` is not able to run your code. You may reproduce the same issue without Quokka by 
- installing `ts-node` (globally or in the project),
- (just for the sake of running the example) changing your `tsconfig.json` `module` setting to `CommonJs` (Quokka does it automatically),
- running: `$ ts-node src/app.ts`.

This happens because when `ts-node` processes your JavaScript, it [can not save compiled JS code](https://github.com/TypeStrong/ts-node/issues/433#issuecomment-334563766) because your `.js` already reside next to your `.ts` files.

> Please note I need all my imports to have the .js extension so they work in the browser.

The only way to make it work I could think of is to remove `.js` extension from imports everywhere in your code, and specify some `outDir` compiler option in your `tsconfig.json`. This way you'll get correct output without `.js` extensions, and `ts-node` will be able to run your code.

**Comment by David-Else** [comment]
@ArtemGovorov If I remove the .js extensions from imports how do I get them back so it works in the browser? I am not sure how this proposal would work.

I am not sure why I need ts-node as Quokka worked fine with TypeScript files out of the box? I read your guide:

> If you are running a quokka file that doesn’t import any other TypeScript files, you don’t need any configuration. You may still import other JavaScript files and node modules.

and that is exactly what I am doing, importing other (compiled) JS files, I don't want to import any .ts files. I saw on that thread that there are options that could be sent to ts-node to solve the problem?

Thanks for helping on a Sunday :)

**Comment by ArtemGovorov** [comment]
> I am not sure why I need ts-node as Quokka worked fine with TypeScript files out of the box?

Quokka runs in node. You wouldn't need `ts-node` if your JavaScript files could be executed in node, but you are compiling them to use ES6 modules, so something needs to compile ES6 modules to CommonJs. If you change your `tsconfig.json` module setting to `CommonJs`, your compiled JavaScript files will not need `ts-node` and will run fine in Quokka.

> If I remove the .js extensions from imports how do I get them back so it works in the browser? I am not sure how this proposal would work.

I don't see how `.js` extensions are related to browser. Correct me if I'm wrong, but you are creating a bundle using rollup, so as I have suggested you can:

>  remove `.js` extension from imports everywhere in your code, and specify some `outDir` compiler option in your `tconfig.json`.

You can the change your rollup config to build the bundle from `outDir` as opposed to be building it from your source code.

Right now your TypeScript code imports JavaScript files (that only gets created when you compile your TypeScript code). Looks like the solution with `outDir` is much cleaner anyway.

**Comment by David-Else** [comment]
Hi, thanks for your help, but I think there is a fundamental misunderstanding. I am not using Rollup to compile as I develop. It is only for the finished shipped product, and it goes through closure compiler. I definitely don't want my entire program going through Rollup every-time I press ctrl-s and want to see the changes in the browser.

I think you have made a mistake saying:

> Right now your TypeScript code imports JavaScript files (that only gets created when you compile your TypeScript code). It means that TypeScript can't even check imported types properly. 

It does import all the types perfectly, I can see them all as I hover over in VS Code, and the software would not even compile if it could not read the types. It is a feature of TypeScript, here is someone else confirming that and a lot of chat on the subject https://github.com/microsoft/TypeScript/issues/16577#issuecomment-343610106

If I switch to commonJS for the sake of Quokka  I get legacy cruft over my code like `Object.defineProperty(exports, "__esModule", { value: true });` so I can use ts-node as a workaround. I don't know why it is needed as Quokka already uses the ESM package and so node can read es6 modules?

I am using es modules everywhere, in TypeScript and in the browser. In order to use es6 modules in the browser, you need a .js file extension. The way my setup works is TypeScript intelligently knows I have to use the .js extension to make it work in the browser so I can use:

`import { checkCollision } from './classes/collision-detection.js';`

and it understands I mean

`import { checkCollision } from './classes/collision-detection.ts';`

or

`import { checkCollision } from './classes/collision-detection';`

so the compiled code keeps the .js extension and it works right out the box in the browser. If I compile everything to another directory then the magic does not work.

I understand that the whole node and es6 modules is a bit of a nightmare, it has been plaguing me a long time now! I just want all the legacy junk to go away and everyone start using the standard that was released 4 years ago and has been supported by all decent browsers for a long long time... I have wasted so much time on this... arrgghhh!

**Comment by ArtemGovorov** [comment]
Thanks for providing the additional details.

> I am not using Rollup to compile as I develop. It is only for the finished shipped product, and it goes through closure compiler.

Got it, I have not realised that you are talking about testing ES modules in browser. I have assumed you are talking about testing production build in a browser because there's rollup build script, but there're no other scripts related to browser testing (like local http server, or browser launcher, or similar).

> It does import all the types perfectly, I can see them all as I hover over in VS Code, and the software would not even compile if it could not read the types. It is a feature of TypeScript, here is someone else confirming that and a lot of chat on the subject

I had no idea about the feature, so indeed my mistake saying: `It means that TypeScript can't even check imported types properly.` Thanks for sharing the link.

> I don't know why it is needed as Quokka already uses the ESM package and so node can read es6 modules?

Right now Quokka is using ESM for JavaScript Quokka files (if Babel or TypeScript is used for Quokka files, Quokka relies on those being able to compile node compatible JavaScript). So if you run Quokka on `src/app.js`, then it'll use ESM. When you run Quokka on TS file, it expects TypeScript/`ts-node` to do the compilation.

Having said that, I think we can add a setting to enable ESM for your scenario (use ESM for JavaScript files that are imported by Quokka and no use `ts-node` for them). We'll discuss it with the team tomorrow and post an update here.

**Comment by David-Else** [comment]
> Having said that, I think we can add a setting to enable ESM for your scenario (use ESM for JavaScript files that are imported by Quokka and no use ts-node for them). We'll discuss it with the team tomorrow and post an update here.

Fantastic news! Cheers :)

**Comment by ArtemGovorov** [comment]
We have added the `stdEsm` setting to enable ESM for your scenario. Now you may remove `allowJs` from your `tsconfig.json` and add `"stdEsm": true` to your Quokka config (global, project or inline one).

**Comment by David-Else** [comment]
Thanks so much for adding this feature!
I am afraid that the test repo I linked you does not work. I have updated Quokka, disabled `allowJs` and added `"stdEsm": true` as you said, I now get:
```
​​​​Quokka 'app.ts' (node: v12.3.1, TypeScript: v3.5.1, plugins: jsdom-quokka-plugin)​​​​

Cannot find module './classes/collision-detection.js' 
Require stack: 
- ./src/app.js 
  at ​src/app.ts:8​
  at ​​​Object.<anonymous>​​​ ​./src/app.js:188​
```
Can you reproduce this? Do I have some setting different from yours?
https://github.com/David-Else/quokka-test
(Please clone it and use the npm run `start-typescript-development` to compile it.)

**Comment by ArtemGovorov** [comment]
I can reproduce the issue (before that I have been trying on new files in project root, and it works, but running on the same files in the src folder doesn't seem to work). It turn out that updating to the latest ESM version 3.2.25 is causing the issue, the previous version 3.2.22 that we have been using seems to work ok.

We have reverted the ESM version to the working one and published the new extension version 1.0.227. Try updating your extension, it should now work.

**Comment by David-Else** [comment]
How unfortunate the ESM people should introduce a regression. It would be great if you could report it to them, I don't think I know enough to explain it.

I just tested again and I think it is all working! The final remaining error on my quokka-test repo is:
```
​​​​Quokka 'app.ts' (node: v12.3.1, TypeScript: v3.5.1, plugins: jsdom-quokka-plugin)​​​​

window.requestAnimationFrame is not a function 
  at ​​​testLoop​​​ ​./src/app.ts:232​
  at ​./src/app.ts:234​
  at ​​​Object.<anonymous>​​​ ​./src/app.js:188​
```
The TypeScript code compiles fine in strict mode and the App runs, do you know why it says this?
Thanks again for adding this awesome new feature.

**Comment by ArtemGovorov** [comment]
Quokka using JSDOM to emulate browser related stuff and [JSDOM only enables `requestAnimationFrame` when `pretendToBeVisual` setting is set](https://github.com/jsdom/jsdom#pretending-to-be-a-visual-browser). You try may passing the [setting as a part of `quokka.jsdom.config` object](https://github.com/wallabyjs/jsdom-quokka-plugin#configuration).

**Comment by David-Else** [comment]
If i use:
```
({
  plugins: ['jsdom-quokka-plugin'],
  jsdom: { file: './index.html', config: { pretendToBeVisual: true } },
});
```
Quokka freezes as does nothing other than printing `​​​​Quokka 'app.ts' (node: v12.3.1, TypeScript: v3.5.1, plugins: jsdom-quokka-plugin)​​​​` on my `app.ts` test repo.

If I do this (wrong I think anyway):
```
({
  plugins: ['jsdom-quokka-plugin'],
  jsdom: { file: './index.html', pretendToBeVisual: true },
});
```
and I still get the `window.requestAnimationFrame` is not a function error

**Comment by ArtemGovorov** [comment]
This
```
({
  plugins: ['jsdom-quokka-plugin'],
  jsdom: { file: './index.html', config: { pretendToBeVisual: true } },
});
```

is the right way to configure it.

I have taken a look in your code and looks like Quokka is working as expected. 

Your program (that Quokka runs in node) never exits (`testLoop`?) and Quokka reports coverage indicators only when a program finishes execution. Try executing the following simple Quokka in anew file:

```js
setInterval(() => {
    console.log(new Date())
}, 1000)
```

and you'll get similar results.

Errors and console logs are still reported in Quokka console, so if you start typing when Quokka is started and introduce an error, you'll see it being reported. If you log something to console, you should get the output in the Quokka console too.

**Comment by David-Else** [comment]
Cheers, now I understand why I got no coverage indicators. I will just have to work around it in development.

I bought the pro version to help me make tutorial videos on TypeScript, and needed the import to work to be able to do that. It is now all looking good to go ahead :)
