### ISSUE TITLE
Visual Studio Code: Live comments not working in non .js files (tired on .es7 file)

### ISSUE THREAD

**Issue by sidferreira** [wallabyjs/quokka#79]
Tried to use quokka in a .es7, and setup Babel to make it into .js files.
But the Live Comments stop working as soon as I save the file as .es7. If I save as .js it still working.

### Quokka.js file

```javascript
const a = true /*?*/
```

### Quokka.js Console Output

```
​​​​Quokka #1 (node: v6.9.1)​​​​

```

### Code editor version

Visual Studio Code v1.? 1.15.1

### OS name and version

OSX 10.12.6

**Comment by ArtemGovorov** [comment]
Everything is working for me if I run Quokka on .es7 file:

![q](https://user-images.githubusercontent.com/979966/29564259-614c3a50-8784-11e7-81b3-676b1e8b9876.gif)

Please describe how to reproduce the issue.

**Comment by sidferreira** [comment]
It is an existing project. I'll retry it tonight.
Maybe I set something wrong...

**Comment by sidferreira** [comment]
Ok, my computer broke and I had to make a fresh install in another one.
Here's the point:
- it is a `firebase functions` project, which means a structure like this:
```
/root
package.json

/root/functions
package.json
index.js
index.es7
```
Visual code is opened in the root folder.
Quokka configurations must be done in the root's  package.json.

After workingproperly (showing the colors at the side of the line numbers) I had to restart the editor. After that the colors are gone. The output still works...

**Comment by ArtemGovorov** [comment]
> After working properly

Considering it worked and the version didn't change, clearly the issue is not with Quokka but with your environment/settings. Perhaps other installed extensions are causing  the issue. To see if that's the case, you may [download VS Code insiders build](https://code.visualstudio.com/insiders), install inly Quokka extension there and try it. If it works, try disabling your extensions one by one and reviewing your settings.

**Comment by sidferreira** [comment]
@ArtemGovorov Current extensions:
- ESLint ( dbaeumer.vscode-eslint )
- JavaScript Standard Style ( chenxsan.vscode-standardjs )
- React Native Tools ( vsmobile.vscode-react-native )
- Sublime Text Keymap ( ms-vscode.sublime-keybindings )

**Comment by ArtemGovorov** [comment]
It may also be your VS Code settings (please share them as well). Try the insiders build as suggested above (without changing its settings).

Also try opening VS Code Dev Tools and:
- check if there are any errors reported in the Console,
- inspect how the gutter looks like?

![q](https://user-images.githubusercontent.com/979966/29613745-c02ef302-884a-11e7-9587-94f1a2b83101.gif)

**Comment by ArtemGovorov** [comment]
Also create a new empty Quokka file (`Cmd + K, J`), type something and check if indicators are displayed there.

**Comment by sidferreira** [comment]
@ArtemGovorov  Tried insiders and had the same issue.

The developer tools had this: 
![captura de tela 2017-08-23 as 08 38 00](https://user-images.githubusercontent.com/143615/29613958-9a01a3a8-87de-11e7-9a54-d19d8683b67b.png)\

Closed VSCode, opened again, no error now.
But found a text area with the label `The editor is not accessible at this time. Press Alt+F1 for options.`:
```
<textarea data-mprt="6" class="inputarea" wrap="off" autocorrect="off" autocapitalize="off" autocomplete="off" spellcheck="false" aria-label="The editor is not accessible at this time. Press Alt+F1 for options." role="textbox" aria-multiline="true" aria-haspopup="false" aria-autocomplete="both" style="font-size: 1px; line-height: 18px; top: 166px; left: 218px; width: 1px; height: 1px; font-family: Menlo, Monaco, &quot;Courier New&quot;, monospace; font-weight: normal; letter-spacing: 0px;"></textarea>
```

Quokka configuration in both places:
```
  "quokka": {
    "babel": {
      "env": "dev"
    }
  }
```

Just noticed that: 
![captura de tela 2017-08-23 as 08 45 50](https://user-images.githubusercontent.com/143615/29614157-85b5ac72-87df-11e7-9b19-d2de340545d9.png)
keeps moving...

**Comment by ArtemGovorov** [comment]
> The developer tools had this

Can't see anything that could stop the indicators from showing up.

> Closed VSCode, opened again, no error now.

Great.

> But found a text area with the label `The editor is not accessible at this time. Press Alt+F1 for options.:`

We don't raise any errors like this in Quokka, must be something else.

**Comment by sidferreira** [comment]
Tried 4 files:
- index.es7 (configured as JS file)
- index.es7.js
- index_es7.js
- index.js

Only the index.js shows the indicators

**Comment by ArtemGovorov** [comment]
I'm running out of ideas. Trying on the same OS, with the same node and babel version, even the same file path, everything is working:

<img width="602" alt="screen shot 2017-08-23 at 9 58 12 pm" src="https://user-images.githubusercontent.com/979966/29614663-5ee66fc2-884e-11e7-902f-3e3a64752391.png">

**Comment by sidferreira** [comment]
I'm really wondering what is the issue.
I have 4 files running at the moment, only the index.js works as expected.
Create a new file works but stops as soon as I save it.

**Comment by ArtemGovorov** [comment]
I managed to reproduce the issue! Not in v1.15.1, but in the insiders build (v1.16.0). Looking into it now.

**Comment by ArtemGovorov** [comment]
The issue is fixed and the fix is published in v1.0.53.

**Comment by sidferreira** [comment]
index.est7 is kinda working now...

but give this error:
```​​Unexpected token import​​
  at ​​​createScript​​​ ​vm.js:74​
  at ​​​Object.runInThisContext​​​ ​vm.js:116​
```

**Comment by ArtemGovorov** [comment]
Looks like babel config is missing (in quokka config). It should show you that it's using babel, like in this sample of yours - https://github.com/wallabyjs/quokka/issues/79#issuecomment-324298794 (that worked for you, except for indicators).

**Comment by sidferreira** [comment]
By any reason the babel config I placed in package.json had some conflict with Quokka.
I'm still having some random issues of the indicators not showing up...
Wondering if it's a computer memory limitation or something...
